# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstellationBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('part', models.PositiveIntegerField()),
                ('right_ascension', models.TimeField(help_text="the position's right ascension for epoch and equinox 2000.0.")),
                ('declination', models.FloatField(help_text="he star's declination for epoch and equinox 2000.0.")),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boundaries', to='celestial.Constellation')),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='right_ascension',
            field=models.TimeField(help_text="he star's right ascension for epoch and equinox 2000.0."),
        ),
        migrations.AlterUniqueTogether(
            name='constellationboundary',
            unique_together=set([('constellation', 'part', 'index')]),
        ),
    ]
