# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0002_Constellation_boundaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='var_max',
            new_name='magnitude_max',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='var_min',
            new_name='magnitude_min',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='var',
            new_name='variable',
        ),
        migrations.AddField(
            model_name='star',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='celestial.Constellation'),
        ),
        migrations.AlterField(
            model_name='object',
            name='right_ascension',
            field=models.FloatField(help_text="he star's right ascension for epoch and equinox 2000.0."),
        ),
    ]
